### GET request with a header
GET http://localhost:8081/api/v1/items
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTYwODkwMDcsImV4cCI6MTcyNzYyNTAwNywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsImZ1bGxOYW1lIjoiSm9obm55IiwidXNlcm5hbWUiOiJlc2hvcEphc2VtIiwiZW1haWwiOiJqcm9ja2V0QGV4YW1wbGUuY29tIiwicm9sZSI6WyJlc2hvcC1kb2N1bWVudC12aWV3ZXIiLCJpdGVtLW1hbmFnZW1lbnQtdmlld2VyIl19.frdtI6OaNs-yECo02AkGwk4R6MxnAK1ed4PDXKThxhE




